version: "3.8"
services:
  n8n:
    image: n8nio/n8n:latest
    ports: ["5678:5678"]
    environment:
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_ENVIRONMENT_VARIABLES_ALLOW_LIST=OPENROUTER_API_KEY,OPENROUTER_MODEL,TAVILY_API_KEY,FIRECRAWL_API_KEY,REDIS_HOST,REDIS_PORT,OLLAMA_HOST,OLLAMA_MODELs
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
      - QUEUE_BULL_REDIS_HOST=redis
      - WEBHOOK_URL=http://localhost:5678/
    depends_on: [postgres, redis]
    env_file: [.env]
    volumes:
      - n8n_data:/home/node/.n8n

  redis:
    image: redis:alpine
    ports: ["6379:6379"]

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports: ["5432:5432"]

  ollama:
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes:
      - ollama:/root/.ollama

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    env_file: [.env]
    environment:
      - RUNNER=python
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
      - OLLAMA_HOST=http://ollama:11434
    ports: ["8080:8080"]
    depends_on: [postgres, redis, ollama]
    volumes:
      - .:/app

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    environment:
      - VITE_API_BASE=/api
    depends_on: [api]
    ports: ["3000:80"]

volumes:
  n8n_data:
  pg_data:
  ollama: